### ISSUE TITLE
Missing description what this is?

### ISSUE THREAD

**Issue by ghost** [ponylang/main.actor#9]
Now, I'm currently going through all repositories of _ponylang_ and I stumbled over this repository. What is this supposed to be? Is this a template for Pony projects? Perhaps you should consider adding a short description in the description field of the repository instead of just referring to the website.

**Comment by SeanTAllen** [comment]
@Shad0wCore It's early work. So there's no description yet. main.actor is going to be a "rubygems like" site for finding pony packages and their documentation (and might eventually grow into something more than that). it's not yet available for public consumption and will have fuller details once it is.

if you are interested in contributing (lots of bash and ruby involved with this project and "devops-y" skills would be involved), let me know.
